apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: dev
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: |
      dev-gateway-forward-prefix@kubernetescrd,
      dev-rewrite-gateway@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  #- host: backend.local
  - http:
      paths:
      - path: /gateway
        pathType: Prefix
        backend:
          service:
            name: gateway-service
            port:
              number: 9090
