apiVersion: v1
kind: Service
metadata:
  name: sso-ui-app
  namespace: dev
  labels:
    app: sso-ui-app
spec:
  type: ClusterIP
  selector:
    app: sso-ui-app
  ports:
  - name: http
    port: 8080
    targetPort: 80
    protocol: TCP
