server:
  port: 9090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      forwarded:
        enabled: true
      routes:
        - id: api1-route
          uri: http://hello-world/
          predicates:
            - Path=/api1/**
          filters:
            - StripPrefix=1
        - id: local-route
          uri: http://192.168.0.114:8080/
          predicates:
            - Path=/local/**
          filters:
            - StripPrefix=1
        - id: auth-route
          uri: http://auth-server/
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: sso-ui-app
          uri: http://sso-ui-app/
          predicates:
            - Path=/sso-ui-app/**
          filters:
            - StripPrefix=1
        - id: oidc-client
          uri: http://oidc-client/
          predicates:
            - Path=/oidc-client/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always