apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  namespace: dev
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: noushadbm/oidc-auth-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
