apiVersion: v1
kind: Service
metadata:
  name: auth-server
  namespace: dev
  labels:
    app: auth-server
spec:
  type: LoadBalancer
  selector:
    app: auth-server
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
